//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLICOSuperpixelsCSharp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SLICOSuperpixelsCSharp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IR_Building {
            get {
                object obj = ResourceManager.GetObject("IR_Building", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MRI_Chest_Axial {
            get {
                object obj = ResourceManager.GetObject("MRI_Chest_Axial", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MRI_Prostate {
            get {
                object obj = ResourceManager.GetObject("MRI_Prostate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help: 
        ///1. Use droplist to specify number of superpixels;
        ///2. Click &quot;Change Image&quot; Button to change image;
        ///3. Click &quot;SLICO&quot; to run superpixel segmentation.
        ///====================
        ///There are three images for demo:
        ///[1] Thermal Image - Building;
        ///[2] MRI Image - Prostate;
        ///[3] MRI Image - Chest Axial;
        ///====================
        ///Thank you, Enjoy ~
        ///.
        /// </summary>
        internal static string strHelpInfo {
            get {
                return ResourceManager.GetString("strHelpInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt; Image reloaded .
        /// </summary>
        internal static string strImageReload {
            get {
                return ResourceManager.GetString("strImageReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLICO Superpixel Segmenation
        ///=====================
        ///-- (C# Code Sample)
        ///By Junjie (Jason) Zhang
        ///junjiezhung@gmail.com
        ///=====================
        ///.
        /// </summary>
        internal static string strProgramInfo {
            get {
                return ResourceManager.GetString("strProgramInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt; Number of superpixel segments: 
        ///.
        /// </summary>
        internal static string strSegmentResult {
            get {
                return ResourceManager.GetString("strSegmentResult", resourceCulture);
            }
        }
    }
}
